infra: 블루그린 무중단 배포
YAPP-Github/23rd-Web-Team-2-BE pull request #13
Opened 2023-12-23 15:14 UTC by shinyubin989

## 관련된 이슈
- close #11

## 작업 사항
<img width="770" alt="image" src="https://github.com/YAPP-Github/23rd-Web-Team-2-BE/assets/69676101/27e1e295-ce5c-4935-ba17-0bc4b2c91a36">
- 블루그린 무중단 배포 설정
- `docker-compose.yml`
  - `${PROJECT_NAME}`, `${DOCKERHUB_USERNAME}`, `${SERVER_ENVIRONMENT}` 등의 환경변수는 각 ec2,ncp의 디폴트 루트내에 .env파일로 정의해두었습니다.
- `Dockerfile`
  - EXPOSE 8080을 제거하였습니다.
- `deploy.sh`
  - green 컨테이너가 떠있으면 blue를 띄운 후 green을 멈추고, blue 컨테이너가 떠있으면 green을 띄운 후 blue를 멈추는 로직을 추가하였습니다.
- `deploy.dev(prod).yml`
  - 기존에 container를 run시키는 로직을 전부 deploy.sh에게 넘겨서 무중단 로직을 수행하도록 변경하였습니다.
- submodule에 `application.yml`
  - shutdown시 graceful하게 종료되도록 하는 옵션을 추가하였습니다.
  - graceful하게 shutdown할 때 데드락 등의 에러로 shutdown이 계속 되지 않는 경우, 30초가 넘으면 자동으로 종료되도록 하는 옵션을 추가하였습니다.

## 기타
- 작업 내용 세부 문서 작성 예정
  - [노션 블로그](https://valley-fog-37a.notion.site/78d286c034fc4907bb56ac5382b99dae?pvs=4)에 업데이트 예정입니다~! 
- 추후 보완사항
  - 현재는 docker container들이 port로 Open되어있어서 인바운드로 80번 포트 말고도 8080포트가 열려있으면 8080으로도 접근 가능한데요, nginx를 도커 컨테이너로 띄운 후 80번 포트만 외부에 오픈한 뒤, api container는 expose로 도커 컨테이너로만 접근 가능하게 구현할 수 있을것같아요! 추후에 구현해보겠습니다

2023-12-24 05:24 UTC, TaeyeonRoyce requested changes
유빈님, 무중단 배포 구성하시느라 고생하셨습니다...!!
고민한 흔적이 많이 보이네요.

몇가지 궁굼한 점들과 수정하면 좋겠다고 생각되는 부분들에 코멘트 남겨두었어요!
의견 남겨주시면 감사하겠습니다.

2023-12-24 05:24 UTC, TaeyeonRoyce commented on docker-compose.yml
> +      - .env
📝
EOF 추가해주세요!

2023-12-24 05:24 UTC, TaeyeonRoyce commented on script/deploy.sh
> +    nginx -s reload
🌗
Green(8080 포트), Blue(8081 포트) 의 포트 포워딩 설정을 각각 만들어서 nginx.conf에 덮어쓰고 있네요!
`nginx.conf` 말고 `sites-available/default`이나 `sites-enable/default`에서 관리하는건 어떨까요?
`nginx.conf`에서 nginx에 대한 전반적인 공통 설정에 대한 관리가 이루어지는 것 같아요. link를 통해 모듈처럼 관리하는 `sites-available/default`에서 포트 변경을 관리하면 관심사도 분리되고, `/etc/nginx/nginx.blue.conf`, `/etc/nginx/nginx.green.conf `도 추가적으로 만들 필요 없어보여요!

${SERVER_PORT} 만 변경하면 되는데 `nginx set variable`도 활용하면 좋을 것 같아요!

2023-12-24 05:24 UTC, TaeyeonRoyce commented on script/deploy.sh
> +  echo "blue -> green"
🌘
보통 blue-green 배포 전략의 경우 blue가 이전 버전, green을 새로운 버전으로 부르는데요.
배포 스크립트를 보면 신/구 버전의 구분보다 A/B의 다른 버전의 의미로 느껴져요!
이렇게 구성한 이유가 있을까요?

2023-12-24 05:24 UTC, TaeyeonRoyce commented on script/deploy.sh
> +    docker-compose -p baro-${BEFORE_COMPOSE_COLOR} stop
🌘
docker compose down 대신 stop을 사용한 이유가 있을까요?

2023-12-24 05:24 UTC, TaeyeonRoyce commented on .github/workflows/deploy-prod.yml
> +            sudo docker image prune -f
🌕
구 버전의 컨테이너와 이미지를 제거하는 플로우도 무중단 배포 스크립트에 포함되면 좋겠어요!

2023-12-24 08:21 UTC, shinyubin989 commented on script/deploy.sh
> +  echo "blue -> green"
저는 blue가 이전버전, green이 새로운버전일때 그 다음 새로운 버전이 나오면 green또한 구버전이 될 수 있다고 생각해서, 블루그린을 A/B의 서로다른 버전과 유사하게 사용했던거같아요.
태연님이 말씀해주신 신/구 버전의 구분이라함은 어떤 의미이실까요??

2023-12-24 08:25 UTC, shinyubin989 commented on script/deploy.sh
> +    docker-compose -p baro-${BEFORE_COMPOSE_COLOR} stop
혹시나 롤백시킬일이 있을때 stop시킨 컨테이너를 재시작하고자 남겨두었던거같아요! 
down시키는게 더 낫다고 생각하실까요??

2023-12-24 11:35 UTC, shinyubin989 commented on script/deploy.sh
> +    nginx -s reload
왜 `sites-available`이랑 `sites-enabled`가 분리되어있나 했었는데, 실제 파일은 `sites-available`에 두고 `sites-enabled`에서 파일을 소프트링크로 연결해둬서 나중에 conf파일을 사용하지않을때 그냥 소프트링크만 제거해서 사용하는 용도군용 

말씀주신 nginx set variable도 `/etc/nginx/sites-available/default` 내에서 사용해봤습니다! 덕분에 `nginx.green.conf`랑 `nginx.blue.conf`가 필요가 없네요 ㅎㅎㅎ 굿굿

[d06c3c2](https://github.com/YAPP-Github/23rd-Web-Team-2-BE/pull/13/commits/d06c3c2d450844f6e431b0b4f71efbc956f67b16)에서 내용 반영해보았습니당

2023-12-25 01:59 UTC, TaeyeonRoyce commented on script/deploy.sh
> +  echo "blue -> green"
새로운 버전을 배포할 때 언제는 그린, 언제는 블루라고 바뀌면서 불리다 보면 헷갈릴 수도 있어서요!
항상 최신 버전을 그린으로, 이전 버전을 블루로 통일해두면 배포시에 헷갈리지 않을 것 같아요.
실행 포트로만 구분하는 걸 생각했어요.
잘 구분해서만 사용하면 문제는 없을 것 같습니다!

2023-12-26 08:07 UTC, shinyubin989 commented on .github/workflows/deploy-prod.yml
> +            sudo docker image prune -f
[2e31d2d](https://github.com/YAPP-Github/23rd-Web-Team-2-BE/pull/13/commits/2e31d2d2548214c4c8290788f9705e1343b689aa) 에서 직전 구버전 이미지, 신버전 이미지만 남겨놓도록 해놨습니당
컨테이너는 deploy.sh에서 제거합니다!


그래서 서버에는 이미지 총 2개, 컨테이너 총 2개만 떠있게 되어있게 해놨습니다

2023-12-26 09:55 UTC, TaeyeonRoyce approved these changes
의견 남겨주시고 리뷰 반영해주신거 확인 했습니다!
고생하셨어요~!!👍

2023-12-26 12:52 UTC, merged