feat: Authentication
YAPP-Github/23rd-Web-Team-2-BE pull request #23
Opened 2024-01-02 17:22 UTC by shinyubin989

## 작업 사항

- tobecontinue

## 기타
-

2024-01-05 15:32 UTC, TaeyeonRoyce requested changes
유빈님, 변경 사항도 많고 코드량도 많은데 고생하셨습니다!
특히, 테스트 부분에서 고민도 많이 하시고 신경쓰신점들이 인상깊었어요!!👍👍

코드량이 많아서 그런지, comment가 좀 많습니다...!
컨벤션 관련하여 사소한 리뷰들도 있는데요. 확인해주시고 반영해주세요!

궁금한 부분들도 꽤 있고, 몇가지 의견 나누어볼 의제들이 있더라고요. 제 의견을 좀 남겼는데, 유빈님 생각도 알려주세요! 
고생하셨습니다!!

2024-01-05 15:32 UTC, TaeyeonRoyce commented on build.gradle
> +}
🌘
version을 따로 관리할 필요가 있나요?

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/application/AuthService.java
> +    public Token signIn(String name, String email, String oauthId, String oauthType) {
🌗
Parameter가 4개나 있는데, `signIn`에 필요한 객체로 정의하는건 어떨까요?

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/application/AuthService.java
> +    }
📝
지금 PR에 추가되는게 아니면 제거하는게 안정할 것 같아요

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/application/TokenTranslator.java
> +}
📝
```suggestion
public interface TokenTranslator {

    Token encode(Member member);
    AuthMember decode(String token);
}
```

2024-01-05 15:32 UTC, TaeyeonRoyce commented on build.gradle
>      implementation 'io.netty:netty-resolver-dns-native-macos:4.1.68.Final:osx-aarch_64'
의존성에 대해 명시해주어서 확인하기 용이하네요!!👍

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/infra/jwt/JwtProperty.java
> +}
📝
```suggestion
@ConfigurationProperties(prefix = "security.jwt.token")
public record JwtProperty(
        String bearerType,
        String secretKey,
        Long accessTokenExpireTime,
        Long refreshTokenExpireTime
) {
}
```

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/exception/jwt/JwtTokenExceptionType.java
> +    NOT_BEARER_TYPE("Bearer 타입이 아닙니다.", HttpStatus.BAD_REQUEST),
🌘
Bearer와 같은 Authorization에서 사용되는 인증 정보는 type보단 scheme라는 용어를 많이 사용합니다!
- https://datatracker.ietf.org/doc/html/rfc6750#section-2.1

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/infra/jwt/JwtTokenCreator.java
> +    Token createToken(Member member, Instant now) {
Token을 생성하는데 `Member`를 의존할 필요가 있을까요?
실제 payload에 들어가는 Long 타입인 id만 받도록 간접참조로 구성하는건 어떠신가요?

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/infra/jwt/JwtTokenCreator.java
> +        var accessToken = Jwts.builder()
📝
`Product` 코드에선 타입추론 보단 명시해주세요!

```suggestion
        String accessToken = Jwts.builder()
```

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/infra/jwt/JwtTokenCreator.java
> +                .compact();
🌘
`RefreshToken`도 accessToken과 같은 key를 사용해도 괜찮을까요?

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/infra/jwt/JwtTokenDecrypter.java
> +    AuthMember decrypt(String authHeader) {
ditto
AuthMember보단 Long타입의 id만 반환하면 어떨까요?

🌗
`authHeader`는 View에 의존적은 워딩인 것 같아요.
`identifier`와 같은 jwt내에서 설명 가능한 워딩은 어떠신가요?

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/infra/jwt/JwtTokenDecrypter.java
> +                    .get("id", Long.class));
🌗 가독성이 안좋은 것 같아요!
```suggestion
            Long id = Jwts.parser().verifyWith(secretKey)
                    .build()
                    .parseSignedClaims(token)
                    .getPayload()
                    .get("id", Long.class);
            return new AuthMember(id);
```

https://tecoble.techcourse.co.kr/post/2020-06-02-law-of-demeter/

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/infra/jwt/JwtTokenDecrypter.java
> +        }
🌕
authHeader가 null인 부분에 대해서도 검증이 필요해보입니다.

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/presentation/AuthController.java
> +    }
ditto

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/presentation/AuthenticationArgumentResolver.java
> +    }
📝 불필요한 `throws`도 제거하고 linebreak도  필요해보이네요.
```suggestion
    @Override
    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
                                  NativeWebRequest webRequest, WebDataBinderFactory binderFactory) {
        String authHeader = webRequest.getHeader("Authorization");
        return translator.decode(authHeader);
    }
    }
```

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/member/application/NicknameCreator.java
> +}
```suggestion
public interface NicknameCreator {

    String createRandomNickname();
}
```

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/member/application/MemberCreator.java
> +    }
🌕
닉네임 생성에 대해서는 개선이 필요해 보입니다.
현재 정해진 방식으로는 `while()`을 통해 계속 `unique `인지 확인하여야 할 것 같은데요.

이 로직은 잠재적으로 굉장히 위험해 보여요.
random성에 의존적이고, 예측 불가한 사용자 데이터(member)에 따라 while loop의 수가 늘어기도 하고, 해당 loop마다 transaction을 점유하고 있어서요.

유니크한 랜덤 닉네임 생성 방식에 대해 적절한 전략을 같이 구성하면 좋을 것 같습니다!

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/member/application/RandomNicknameCreator.java
> +                Nouns.values()[(int) (Math.random() * Nouns.values().length)].getNoun();
🌕
형용사(Adjectives)에서 랜덤한 값을 꺼내는 로직은 `Adjectives.class`의 역할일 것 같네요.
잘 분배하면 아래처럼 만들 수 있을 것 같아요.

```java
Adjectives.pickRandom() + Nouns.pickRandom();
```

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/member/domain/Adjectives.java
> +public enum Adjectives {
🌘
`Adjectives` 와 같은 범용어는 다른 도메인에서도 사용될 수 있어요.
`MemberNameAdjectives` 처럼 의미를 담는건 어떨까요?

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/member/domain/Adjectives.java
> +    }
📝
`@RequiredArgsConstructor` 로 대체해도 좋아보이네요

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/common/auth/AuthMember.java
> +package com.baro.common.auth;
🌘
`auth`가 아닌 `common.auth`에 두신 이유가 있을까요?

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/member/domain/Member.java
>      }
id가 필요한 상황(ex. test)에 대해 생성자를 따로 두는 방법 좋습니다!!👍👍

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/member/domain/Nouns.java
> +    EXAMPLE_NOUN2("명사2"),
```suggestion
📝
@Getter
public enum Nouns {

    EXAMPLE_NOUN1("명사1"),
    EXAMPLE_NOUN2("명사2"),
```

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/member/domain/Adjectives.java
> +    EXAMPLE_ADJECTIVE1("형용사1"),
📝
```suggestion
@Getter
public enum Adjectives {

    EXAMPLE_ADJECTIVE1("형용사1"),
```

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/main/java/com/baro/member/domain/Nouns.java
> +    }
ditto

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/application/oauth/OAuthInfoProviderTest.java
> +//    }
🌗
사용 되지 않는 테스트라면 지워주세요

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/domain/TokenTest.java
> +                new Token("accessToken", "refreshToken"));
🌘
일관되게 `assertj`만 사용하는건 어떨까요?

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/presentation/AuthenticationArgumentResolverTest.java
> +                    .get("/test/auth");
📝
```suggestion
        Response response = RestAssured
                .given()
                .log().all()
                .contentType(MediaType.APPLICATION_JSON_VALUE)
                .when()
                .header("Authorization", testToken)
                .get("/test/auth");
```

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/presentation/AuthenticationArgumentResolverTest.java
> +    void 매개변수에_AuthMember가_존재하는경우_Argument_resolver를_거친다() throws Exception {
📝
```suggestion
    void 매개변수에_AuthMember가_존재하는경우_Argument_resolver를_거친다() {
```

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/presentation/oauth/OAuthApiDocumentTest.java
> +//    }
ditto

2024-01-05 15:32 UTC, TaeyeonRoyce commented on src/test/java/com/baro/common/time/fake/FakeTimeServer.java
> +    }
```suggestion
public class FakeTimeServer implements TimeServer {

    @Override
    public Instant now() {
        return Instant.from(LocalDateTime.of(2024, 1, 1, 0, 0, 0));
    }
```

2024-01-06 16:52 UTC, shinyubin989 commented
@TaeyeonRoyce 태연님! 리뷰 남겨주신것 & 오늘 의논한것 적용해서리팩토링 ([리팩토링커밋](https://github.com/YAPP-Github/23rd-Web-Team-2-BE/pull/23/files/51d3c24580bcd73898fea34521aa43a160798440..120594e60393f4b04239cfdde2e97f8e093da335)) 한 부분입니다~!~! 확인 부탁드려요 👾

2024-01-07 04:52 UTC, shinyubin989 commented
저희 서비스에서 쓰일일이 거의 없긴한데, 아래와같이 트랜잭션 격리레벨을 `READ_UNCOMMITED`로 낮춰서 동시성을 제어하는 방법도 있다고 하더라구요

```java
@Transactional(isolation = Isolation.READ_UNCOMMITTED)
public Something create(A a, B b) {

    repository.save(new Something(a,b));

    repository.findByA(a)
            .ifPresentOrElse(
                    // throw RuntimeException으로 롤백
            );
}
```
태연님 이미 알고계실 수 있지만 ㅎㅎ
갠적으로 동시성 제어하려면 격리레벨을 올려야 안전하다고 생각했었는데 역으로 격리레벨을 낮춘후에 동시성을 제어하는 방식도 있더라구요
신기해서 함 공유해봅니당

2024-01-07 22:26 UTC, TaeyeonRoyce requested changes
유빈님 수고하셨습니다~!

몇가지 컨벤션이랑 `Authorization`에서 Null에 대한 검증이 아직 적용되지 않은 것 같아요.
확인하시고 다시 PR주세요!

2024-01-07 22:26 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/domain/TokenTest.java
>      }
이전 리뷰에서 놓친건데, 이 테스트는 어떤걸 테스트하는건가요?

2024-01-07 22:26 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/infra/jwt/JwtTokenDecrypter.java
> +        throw new JwtTokenException(JwtTokenExceptionType.NOT_BEARER_TYPE);
여전히 `NPE`에 대해선 오류가 발생 할 것 같네요.

2024-01-07 22:26 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/infra/jwt/TokenCreator.java
> +package com.baro.auth.infra.jwt;
`com.baro.auth.application`에 위치시키는건 어떨까요?

2024-01-07 22:26 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/infra/jwt/TokenDecrypter.java
> +package com.baro.auth.infra.jwt;
ditto

2024-01-07 22:26 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/domain/AuthMemberTest.java
> +    }
ditto

\+ assertj로 통일하죠!

2024-01-07 22:26 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/infra/jwt/JwtTokenDecrypterTest.java
> +        Token token = creator.createToken(1L, timeServer.now());
📝
```suggestion
    @Test
    void 정상적인_액세스토큰에_대해_복호화한다() {
        // given
        Token token = creator.createToken(1L, timeServer.now());
```
다른 테스트들도 공백이 추가되어있네요..ㅠ

2024-01-07 22:26 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/domain/Token.java
> +}
📝
```suggestion
public record Token(
        String accessToken,
        String refreshToken
) {
}
```

2024-01-07 22:26 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/infra/jwt/JwtTokenDecrypter.java
> +    public Long decrypt(String authHeader) {
authHeader라는 모호한 view용어보단 `decrypt()`역할에 맞는 인증 정보 `authroization`은 어떨까요
```suggestion
    public Long decrypt(String authorization) {
```

2024-01-08 03:38 UTC, shinyubin989 commented on src/test/java/com/baro/auth/domain/TokenTest.java
>      }
도메인 객체인 Token의 내부 필드가 동일하다면 값객체로서 동일함을 테스트하였습니다.

2024-01-08 05:54 UTC, TaeyeonRoyce approved these changes
코멘트 반영한거 확인했습니다.

고생하셨어요! confilct만 확인하시고 merge해주세요!

2024-01-08 06:37 UTC, merged