feat: reissue
YAPP-Github/23rd-Web-Team-2-BE pull request #29
Opened 2024-01-09 05:04 UTC by shinyubin989

## 관련된 이슈

BAR-173

## 작업 사항

- 토큰 재발급 로직을 구현하였습니다.
- 리프레시 토큰 내에 ip 정보를 담아서, 재발급 요청시 요청자의 ip와 리프레시토큰 내의 ip 동일여부를 판단하였습니다.
    - 이때 리프레시 토큰 내에 ip는 AES 알고리즘으로 암호화하였습니다.
- nginx등의 프록시를 사용할 경우 ip 정보가 127.0.0.1등으로 변경되어, nginx의 `sites-available` 파일에 요청자의 ip를 "X-Forwarded-For"에 쌓이도록 하였습니다.
- 현재는 nginx프록시만을 사용하여 "X-Forwarded-For"의 헤더에 대해서만 ip를 추출하나, 추후에 프록시와같은 구성이 추가될 경우 아래와같이 헤더를 담는 enum을 추가해도 좋을 것 같습니다.
```java
    @RequiredArgsConstructor
    @Getter
    enum IpHeaderCandidates {
        X_FORWARDED_FOR("X-Forwarded-For"),
        PROXY_CLIENT_IP("Proxy-Client-IP"),
        WL_PROXY_CLIENT_IP("WL-Proxy-Client-IP"),
        HTTP_CLIENT_IP("HTTP_CLIENT_IP"),
        HTTP_X_FORWARDED_FOR("HTTP_X_FORWARDED_FOR"),
        HTTP_X_FORWARDED("HTTP_X_FORWARDED"),
        HTTP_X_CLUSTER_CLIENT_IP("HTTP_X_CLUSTER_CLIENT_IP"),
        HTTP_FORWARDED_FOR("HTTP_FORWARDED_FOR"),
        HTTP_FORWARDED("HTTP_FORWARDED"),
        HTTP_VIA("HTTP_VIA"),
        REMOTE_ADDR("REMOTE_ADDR"),
        ;

        private final String name;
    }
```
- 리프레시토큰의 경우 redis에 "RT:${memberId}"의 key 형태로 저장하였습니다.

## 기타
- 리프레시토큰 없이 액세스토큰만 가지고 가는 방법도 생각해보았는데, 이렇게되면 끄적이는 페이지에서 글을 끄적이다가 토큰이 만료되어 다시 로그인 화면으로 가게되는 시나리오가 충분히 발생할 거라고 생각했습니다. 
- 그래서 리프레시토큰을 꼭 가지고가되, 액세스토큰과 리프레시토큰이 둘다 탈취되었을경우 최대한 재발급요청이 불가능하게끔 하는 로직을 생각해보았고 이에 ip를 써보자고 생각하게되었어요.
- ip로 검증하는 방식보다 더 안전한 방법/ 혹은 리팩토링 사항이 있다면 피드백 부탁드려요! 반영해보겠습니다.

2024-01-10 04:47 UTC, TaeyeonRoyce commented
IP를 통해 탈취 케이스에 대비하여 고민하신점이 인상깊네요.
몇가지 고려해볼 사항들이 있어서 의견을 좀 남겨볼게요.

IP를 통해 리프레시 토큰을 검증한다면 사용자에게 불편함을 야기 할 수 있을 것 같아요.
예를 들어, 집에서 Baro에 로그인하여 사용하다가 노트북을 들고 카페에서 사용하는 경우에도 로그인이 풀리고요.
다른 기기(모바일, 회사 PC 등)에서 Baro에 로그인하면 기존에 로그인 되어있던 기기에서도 리프레시토큰이 유효하지 않게 되겠죠.
제가 사용하는 대부분의 서비스에서는 장소를 이동하여 다른 IP주소를 사용해도 로그인이 풀리지 않아서요.

보안과 사용자 편의성에서 트레이드오프가 있는 것 같은데, 저희가 IP주소를 통한 검증을 마음대로 넣기에는 그 영향도가 큰 것 같습니다.
IP도 개인정보로 보는 측이 많아서 개인정보 처리 방침에 IP 수집도 추가되어야 하고요. 글자만 추가하는거라 어렵진 않지만, 기획자분께서 인지하고 계셔야 하기도 하고요.
팀 단위 회의에서 `사용자의 로그인/로그인 유지 경험`에 대해 명확하게 정의하고 보안이 중시되면 적용하도록 하는 건 어떨까요?
현재 PR의 영향도가 단순하게 `탈취 취약점에 대해 대비` 가 아니라 사용자 경험에도 미치는 것 같아요.
IP에 의존적으로 로그인이 유지되는 경우에 대해서 회의를 나누면 좋을 것 같습니다.

다시 원론적인 물음으로 돌아오면, 액세스토큰과 리프레시토큰이 탈취되는 경우에 대해 고민해보죠.
대표적으로 `XSS`, `CSRF` 공격에 의해 탈취된다고 하는데요. 
잘 알려진 공격에 대해서 Refresh token을 `http-only cookie` 로 설정하는 방법도 있겠네요.
저희 서비스가 특별하게 높은 보안 레벨이 필요하다면 서버에서 관리하지 못하는 토큰 방식을 고수해야 하는지도 고민해볼 필요가 있겠죠.
RTR 이란 방법도 있습니다!
이런 관점에서도 고민해보셨을까요?

유빈님이 생각하신 아이디어가 토큰의 보안상의 단점을 많이 메꾸어주는것 같아요.
IP를 다루고 암호화 하는 로직에 대해 고민 많이하시고 코드와 테스트까지 잘 짜주셨습니다!
이 방식에 대해선 팀 회의에서 의논해보고 결정하면 어떨까요? 의견남겨주세요!

2024-01-10 07:53 UTC, shinyubin989 commented
> 집에서 로그인하다가 카페로 간 경우
- IP로 구성할때는 ‘집에서 바로 서비스를 사용하다가 카페로 간 경우’에는 로그인을 다시 해야한다고 가정하고 로직을 구성했는데, 말씀해주신 경우에도 reissue가 되면 좋을것같네요!

코멘트 남겨주신 것 토대로 밑에 “1. AT만 사용”, “2. AT,RT 모두 사용”하는 경우의 수에 문제를 해결할 방법을 정리해보았어요.

<br />

> Access Token만 사용할 경우
1. `Sliding Session` 방식 사용
    - 글 작성/수정 시작시 작성중 토큰이 만료되는 경우를 막기 위해 새로 토큰을 발급하는 등 지속적으로 서비스를 이용중인 유저에게 토큰의 만료기한을 늘려주는 방법
    - 장점 : 로그인을 자주할 필요없고, RT필요없음. 또 인증 유지가 필요한 경우 토큰이 만료되는 문제를 방지할 수 있음
2. 혹은 AT만료시 작성중이던것(끄적이는글, 수정중인글)이 일시적으로 저장된다면 sliding session 없이 AT만 가져가도 좋을것같아요.

> AT와 RT 모두 사용할 경우
- XSS 공격 대비
    - cookie에 `http only option`을 통해 방어 (+ `secure cookie option`을 통해 https인 경우에만 cookie가 전송되도록)
- Sniffing 공격 대비
    - HTTPS를 통해 중요 정보 노출에 대비해 정보암호화 -> 완료
- CSRF 공격 대비
    - `SameSite option`
    - Cross Site 요청의 경우 쿠키 전송을 제약하는 `Strict` || `Lax`를 설정
        - `Strict` - 가장 보수적인 정책. 크로스 사이트 요청에는 항상 전송되지 않음. 서드 파티 쿠키는 전송되지 않고, 퍼스트 파티 쿠키만 전송
        - `Lax` - Strict에 비해 상대적으로 느슨한 정책. 대체로 서드 파티 쿠키는 전송되지 않지만, 몇 가지 예외적인 요청에는 전송
        - [참고](https://seob.dev/posts/%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80-%EC%BF%A0%ED%82%A4%EC%99%80-SameSite-%EC%86%8D%EC%84%B1/)

> 여러 기기로 로그인한경우에, 하나의 멤버에 대해 RT를 저장하는 방법
1. Http Header의 `User-Agent`와 같은 정보를 토대로 기기마다 각기 다른 RT를 생성후 저장하는 방법
2. 최근 로그인한 기기를 기준으로 활성화 멤버를 결정하는 방법 (이전 로그인 기기에서는 재로그인 필요)

> HTTPS로 통신하면 이미 정보들이 다 암호화되어있으므로 탈취되어도 괜찮지않나?
- 놉.. `SSL strip`, `MITM`(중간자) 공격 등으로 HTTPS를 뚫을 수 있음.

> RTR
- Refresh token에 재발급 가능한 count 수를 담아 사용

<br />


우선 요정도 정리해보았는데, 오늘 회의에서 준희님께 사용자 인증 정책에 관해 여쭤보고 백엔드 회의 통해 인증정책을 결정해보는건 어떨까요?

코멘트 남겨주신부분 읽어보고 찾아보면서 많이 배운거같아요! 추가적으로 생각해보니 모바일 환경에서는 와이파이->데이터 등 ip환경이 바뀔 일이 잦겠더라구요. 또 IP 개인정보 등 문제가 될부분도 인지하게되었어요 😅  회의통해서 인증정책이 결정되면, 다시 리팩토링해보도록 할게요! 리뷰남겨주셔서 감사합니다

2024-01-11 12:21 UTC, shinyubin989 commented
@TaeyeonRoyce 태연님 리뷰부탁드려요!
refresh token payload에 아무것도 안담고, 재발급시 AT,RT 모두 새로 발급하도록 구현했습니다. 
`TokenTranslator::decodeRefreshToken(String token)`이 메소드명은 decode인데 반환값은 void인게 좀 불편한데 마땅한 메소드명이 떠오르지않아서 일단 `decodeAccessToken()`과 통일성있게 해놨습니다.

2024-01-11 12:24 UTC, TaeyeonRoyce commented
이번 PR 범위만 줄여서 올려주실 수 있나요?
커밋이 많아서 모아보기가 잘 안되네요ㅠ

2024-01-11 12:29 UTC, shinyubin989 commented
@TaeyeonRoyce [수정 커밋 범위](https://github.com/YAPP-Github/23rd-Web-Team-2-BE/pull/29/files/5b3ec3fe2e897a76bbbf8007077251d3013be20f..91d3b3cdaa5ac684ff81fc0065a6cf4d1dcdd72b)입니다~~

2024-01-11 12:33 UTC, TaeyeonRoyce commented
[chore: submodule 업데이트](https://github.com/YAPP-Github/23rd-Web-Team-2-BE/pull/29/commits/681ebf19fec015d6a02710a577f42e7090457947)  ~ [refactor: refresh token decode메소드명 변경](https://github.com/YAPP-Github/23rd-Web-Team-2-BE/pull/29/commits/91d3b3cdaa5ac684ff81fc0065a6cf4d1dcdd72b) 를 보려한거였습니다!
commit에 스크롤이 생기니깐 범위 설정이 안되더라고요..

다른 PR이랑 섞여있는거를 제거해주세요..! 
[feat: Kakao 로그인 후 이메일 정보 저장](https://github.com/YAPP-Github/23rd-Web-Team-2-BE/pull/29/commits/b7e2b1f0750e027dc2f0cc7d70fa6f6b3aa5450e) ~ [refactor: Clean up test codes](https://github.com/YAPP-Github/23rd-Web-Team-2-BE/pull/29/commits/ac37fcfaa1edbb05eead7d8cfc1ca85df16e3a01)

2024-01-11 13:11 UTC, shinyubin989 commented
아아 잠시만 기다려주시겠어요

2024-01-11 13:12 UTC, TaeyeonRoyce commented
@shinyubin989 url로 범위 선택해서 찾긴 했습니다!

2024-01-11 13:15 UTC, TaeyeonRoyce requested changes
유빈님, 고생하셨어요!

url변경하니 범위 선택이 되네요...!
메서드 네이밍 관련해서 의견 남겨두었습니다.

이외 코멘트도 확인해주세요! 수고하셨습니다.

2024-01-11 13:15 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/application/AuthService.java
> +            throw new AuthException(AuthExceptionType.REFRESH_TOKEN_DOES_NOT_EXIST);
`tokenTranslator.decodeRefreshToken(refreshToken);` 이 호출되기 전부터 null 검증이 이루어져야 할 것 같습니다.

2024-01-11 13:15 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/infra/jwt/JwtTokenDecrypter.java
> +        if (authorization == null) throw new JwtTokenException(JwtTokenExceptionType.AUTHORIZATION_NULL);
아래도 한줄짜리 조건문인데 블럭이 있고, `AuthService.validateRefreshToken()`에는 블럭 없이 줄바꿈이 었었는데요.
일관성을 지키면 좋을 것 같네요!

2024-01-11 13:15 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/application/AuthServiceTest.java
> +        assertEquals(tokenStorage.findRefreshToken(String.valueOf(1)), token.refreshToken());
AssertJ로 변경하면 좋을 것 같아요

2024-01-11 13:15 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/application/AuthServiceTest.java
> +        assertThrows(AuthException.class, () -> authService.reissue(1L, token.refreshToken()));
ditto

2024-01-11 13:15 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/fake/jwt/FakeTokenStorage.java
> +        else throw new JwtTokenException(JwtTokenExceptionType.EXPIRED_JWT_TOKEN);
일관성 맞춰주세요!

2024-01-11 13:15 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/presentation/oauth/OAuthApiDocumentTest.java
> +                ));
사용 되지 않는 것 같습니다. 제거해주세요

2024-01-11 13:15 UTC, TaeyeonRoyce commented on src/test/java/com/baro/auth/presentation/oauth/OAuthApiDocumentTest.java
> +    void reissue() {
AuthApiDocument로 옮기는건 어떨까요?
\+ 실패 케이스에 대한 테스트도 추가하면 좋을 것 같습니다

2024-01-11 13:15 UTC, TaeyeonRoyce commented on src/main/java/com/baro/auth/application/AuthService.java
> +        validateRefreshToken(memberId, refreshToken);
말씀대로 `decode`를 하는데 반환값이 없으니 어색하네요...!
해당 메서드를 보니 리프레시 토큰이 유효한지 검증을 하고 있는데요.
`validateRefreshToken`을 사용하는게 좋아보여요.

아래 `validateRefreshToken(memberId, refreshToken);` 이 메서드 이름을 수정하는건 어떨까요?
`refreshToken`의 유효성 검사보단 이미 유효한 refreshToken에 대한 요청을 검증하는 것 같네요.
`validateRefreshTokenOwner`, `matchRefreshTokenOwenr`처럼 더 구체적인 네이밍도 좋아보여요.

2024-01-12 12:26 UTC, TaeyeonRoyce approved these changes
리뷰 반영 된 거 확인했습니다!
- #27 내용들이 커밋에 포함되어 있어서 conflict가 생긴 것 같습니다.

커밋 포함해서 conflict를 해결 해두신 것 같긴 한데, 이전 커밋들 정리하고 머지해도 괜찮을 것 같네요!
결과물은 같아서 그냥 머지하셔도 괜찮습니다!

2024-01-13 05:47 UTC, merged