feat: 템플릿 복사 횟수 증가
YAPP-Github/23rd-Web-Team-2-BE pull request #44
Opened 2024-01-18 04:55 UTC by shinyubin989

## 관련된 이슈

BAR-212

## 작업 사항

- 템플릿 복사 횟수를 증가시키는 api 로직을 구현하였습니다.

2024-01-18 13:51 UTC, TaeyeonRoyce requested changes
유빈님, 고생하셨습니다👍👍

코멘트 남겨두었는데 확인해주세요!

2024-01-18 13:51 UTC, TaeyeonRoyce commented on src/main/java/com/baro/memo/application/dto/CopyTemplateCommand.java
> +package com.baro.memo.application.dto;
🌗
template에 더 적합해 보여요
```suggestion
package com.baro.template.application.dto;
```

2024-01-18 13:51 UTC, TaeyeonRoyce commented on src/main/java/com/baro/template/application/TemplateService.java
> +        Member member = memberRepository.getById(command.memberId());
🌗
`Member`는 사용 되지 않고 있는데 제거하면 어떨까요?

2024-01-21 13:51 UTC, shinyubin989 commented on src/main/java/com/baro/template/application/TemplateService.java
> +        Member member = memberRepository.getById(command.memberId());
그렇네요 추후에 로직내에 멤버가 필요해지면 나중에 추가하겠습니다!

2024-01-22 03:02 UTC, TaeyeonRoyce approved these changes
고생하셨습니다!!

2024-01-22 05:28 UTC, merged