refactor: 아카이브 테이블 구조 변경
YAPP-Github/23rd-Web-Team-2-BE pull request #48
Opened 2024-01-24 14:30 UTC by shinyubin989

## 관련된 이슈

BAR-226

## 작업 사항

- Memo, TemplateMember를 제거하고 Archive로 통합하였습니다.
- flyway를 업데이트하였습니다.
- 다 엉켜있다보니 커밋을 쪼갤수가없어서.. 하나의 커밋이 되어버렸어요 😱

2024-01-24 15:13 UTC, TaeyeonRoyce requested changes
고생하셨어요 유빈님!
테이블 설계도 고민 많이 하시고 좋은 방식으로 변경 된 것 같습니다.

관련해서 한가지 궁금한 점 코멘트 남겨두었는데 확인해주세요!
그리고 DB에서 text type으로 변경된 부분에 대해 code에서도 반영해주어야 할 것 같아 리뷰 남겨두었습니다!

2024-01-24 15:13 UTC, TaeyeonRoyce commented on src/main/java/com/baro/archive/presentation/ArchiveController.java
> +    @PostMapping("/temporal-memos/{temporalMemoId}")
끄적이는 메모를 아카이브 하는 행위에 대해서 이전 표현인 `/temporal-memos/{temporalMemoId}/archive` 가 저는 더 명확해 보여요. 아래 template도 그렇고요!

혹시 `/archives/temporal-memos/{temporalMemoId}`로 설계하신 이유가 궁금합니다

2024-01-24 15:13 UTC, TaeyeonRoyce commented on src/main/java/com/baro/memo/domain/TemporalMemo.java
>      private MemoContent correctionContent;
Entity에도 text로 변경 된 점을  반영해야 할 것 같습니다

2024-01-24 15:26 UTC, shinyubin989 commented on src/main/java/com/baro/archive/presentation/ArchiveController.java
> +    @PostMapping("/temporal-memos/{temporalMemoId}")
archive 도메인으로 넘어간 이상 archive가 먼저 오는게 맞겠다고 생각했어요!
앞으로 추가될 GET archives같은 동작이 ArchiveController에서 구현될테니, RequestMapping이 통일되면 좋겠다 싶었습니다.

태연님이 `/temporal-memos/{temporalMemoId}/archive`가 적합하겠다고 생각하신 이유는 무엇일까요??

2024-01-25 01:45 UTC, TaeyeonRoyce commented on src/main/java/com/baro/archive/presentation/ArchiveController.java
> +    @PostMapping("/temporal-memos/{temporalMemoId}")
저는 저희 서버에서 정의한 도메인 엔티티와 API로 제공하는 자원은 다르다고 생각해서 네이밍이나 컨텐츠들을 통일 시킬 필요는 없다고 생각하는데요.
GET archives 같은 경우에는 `ArchiveController`에서 이루어지는 부분에 대해서는 동의합니다!

`archive`가 추가되는 경우가 `temporalMemo` -> `archive`, `Template` -> `archive` 인데, 이걸 표현하면 어떨까 생각이 들었습니다. `끄적이는`의 관심사에 더 부합 하다고 생각했었어요! TemporalMemos에서 해결되어야 하는 기능이라 생각했었거든요.

공통 컨텐츠 저장소의 성격이 강한 `archive`가 애매한 부분이 있다고 생각해요.
특히, archive delete나 patch 같은 경우에는 항상 template, memo가 구분 되어야 하고요.
컨텐츠가 더 추가되면 `PATCH /archive/new-contents/{}`, `DELETE /archive/new-contents/{}`처럼 슈퍼(?) 클래스가 될 것 같기도 해서요.
의존성도 여러 컨텐츠가 아카이브를 의존하는게 유지보수에도 나아보여요! 이벤트로 분리 하기도 좋고 확장성도 좋다고 생각합니다..!
이런 이유로 말씀드렸었습니다.

2024-01-25 03:52 UTC, shinyubin989 commented on src/main/java/com/baro/archive/presentation/ArchiveController.java
> +    @PostMapping("/temporal-memos/{temporalMemoId}")
1. 컨텐츠가 추가될때 슈퍼클래스가 된다는부분에서 이해가 잘 안되었는데요, 제가 이해한 바로는 이 문제는 두 방식 모두 동일할 것 같은데 슈퍼클래스가 된다는건 어떤걸까요?

2. 여러컨텐츠가 아카이브를 의존한다는게 temporalMemo, template에서 아카이브를 하는 로직이 TemporalMemoService, TemplateService에서 수행돼야한다는 의미일까요??
아카이브 POST,DELETE는 각 TemporalService, TemplateService에서 / 아카이브 GET,PATCH는 ArchiveService에서 <-를 말씀하신게 맞을까요?

2024-01-25 04:28 UTC, TaeyeonRoyce commented on src/main/java/com/baro/archive/presentation/ArchiveController.java
> +    @PostMapping("/temporal-memos/{temporalMemoId}")
1. 클래스가 비대해진다는 말이었습니다. 헷갈리는 용어 사용해서 죄송해요...!
지금은 `temporal-memos`, `templates` 두 개의 컨텐츠를 저장하고 있는데요.
컨텐츠가 늘어났을 때, 계속해서 archive에 계속 추가되어야 한다는 의미였습니다.
예를 들어 사용자의 글도 archive를 해야 한다면, ArchiveController에 `POST /archive/posts/{}, DELETE /archive/posts/` 코드가 계속 추가 될 것 같아서요.

Post에서 처리한다면 해당 컨텐츠를 archive하는데 PostController에서 처리되구요.

2. 넵 맞습니다.

---
제가 고민한 부분은 `acrhive` 독립적으로 설명 가능 한 spec이 없는 부분이었습니다.
`/archives/temporal-memos`, `/archives/template` , `/archives/xxx` 로만 정의 가능한 상태인데,
"`archive`를 독립된 하나의 자원으로 볼 수 있는가"에 대해 고민한 것 이었습니다.

아니면 Type column을 추가해서 `archive`만으로 설명 가능하게 정의하면 어떨까요

```javascript
POST '/archives'
{
    // 기존 컬럼들...
    "type": TEMPLATE // or MEMO
}
```
클라이언트측에서도 `아카이브`를 추가하는 url을 구분해서 생각할 필요도 없기도 하고
`archive`하나의 표현으로 template, temporal-memo에 대해 삭제나 수정에 대한 각각의 동작을 구분하여 수행 할 수 있을 것 같아요.

`POST /archive/1`
-> type을 통해 코드(application)에서 분리 하여 로직 수행

2024-01-26 05:19 UTC, shinyubin989 commented on src/main/java/com/baro/archive/presentation/ArchiveController.java
> +    @PostMapping("/temporal-memos/{temporalMemoId}")
위에서 말씀해주셨던 
> 끄적이는의 관심사에 더 부합 하다고 생각했었어요! TemporalMemos에서 해결되어야 하는 기능이라 생각했었거든요.

에 동의합니다!  그런데 바디에 담기보다는, 처음에 말씀해주신 url에 담는 방법은 어떨까요? (ex `/temporal-memos/{temporalMemoId}/archive`) 
화면상으로도 끄적이는 페이지에서의 동작이기도하고, url적으로 의미가 더 잘 표현되는것같아요 !

2024-01-26 05:39 UTC, TaeyeonRoyce commented on src/main/java/com/baro/archive/presentation/ArchiveController.java
> +    @PostMapping("/temporal-memos/{temporalMemoId}")
넵 저는 좋습니다..!

2024-01-26 06:15 UTC, TaeyeonRoyce approved these changes
변경 사항이 많은데 잘 적용해주셨네욥
고생 하셨습니다!👍👍

2024-01-26 06:23 UTC, merged